// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("Sniper")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
[assembly: ComVisibleAttribute(false)]
namespace System
{
    internal static class AssemblyVersionInformation
    {
        internal const string Version = "0.1.0";
        internal const string InformationalVersion = "0.1.0";
    }
}
